Repository mao-wfs/mao-merge-45m, pull requests merged in 2022-09, with the labels that each got.

#41 Add support for Poetry >=1.2
  .devcontainer/Dockerfile
  poetry.lock
  pyproject.toml
Labels: environment

#43 Do not use append method of DataFrame
  mao_merge_45m/antenna.py
  mao_merge_45m/weather.py
Labels: bug

#44 Add support for new 50-sps antenna logs
  mao_merge_45m/antenna_50sps.py
Labels: feature

#46 Rename module (antenna_50sps.py -> antenna_50_sps.py)
  mao_merge_45m/__init__.py
  mao_merge_45m/antenna_50_sps.py
Labels: feature

#47 #37 Add support for SAM45 logs
  mao_merge_45m/__init__.py
  mao_merge_45m/sam45.py
Labels: feature

#49 #48 Fix timestamp to yymmdd
  mao_merge_45m/antenna_50_sps.py
Labels: bug

#51 #50 Add a sentence to get_df that eliminates duplicate timestamps
  mao_merge_45m/antenna_50_sps.py
Labels: bug

#53 #52 Replace real_Z1 and real_Z2.
  mao_merge_45m/antenna_50_sps.py
Labels: bug

#55 Update calibration method of SAM45 logs
  mao_merge_45m/sam45.py
Labels: feature

#60 Add argument of SAM45 log path to merge function
  mao_merge_45m/merge.py
  tests/test_merge.py
Labels: feature

#63 Make function options keyword-only arguments
  mao_merge_45m/accelerometer.py
  mao_merge_45m/antenna.py
  mao_merge_45m/antenna_50_sps.py
  mao_merge_45m/correlator.py
  mao_merge_45m/merge.py
  mao_merge_45m/sam45.py
  mao_merge_45m/weather.py
  tests/test_merge.py
Labels: feature

#66 Update README
  README.md
Labels: docs

#68 Fix SAM45 timestamp to datetime64[ns]
  mao_merge_45m/sam45.py
Labels: bug
