Repository mao-wfs/mao-merge-45m, pull requests merged in 2023-07, with the labels that each got.

#78 #75 Add options to shift timestamps of logs
  mao_merge_45m/merge.py
Labels: feature

#80 Fix wrong data_vars/coords assignment in merge module
  mao_merge_45m/merge.py
  tests/test_merge.py
Labels: bug

#84 Add merge information to merged Zarr
  mao_merge_45m/merge.py
Labels: feature

#85 Release v0.2.0
  mao_merge_45m/__init__.py
  pyproject.toml
  tests/test_metadata.py
Labels: release

#87 Fix missing long_name of time coordinate
  README.md
  mao_merge_45m/__init__.py
  mao_merge_45m/merge.py
  pyproject.toml
  tests/test_metadata.py
Labels: bug, release
