Repository mao-wfs/mao-merge-45m, pull requests merged in 2023-11, with the labels that each got.

#94 Add thermometer module
  data/thermometer_20220430T150000.txt
  mao_merge_45m/__init__.py
  mao_merge_45m/merge.py
  mao_merge_45m/thermometer.py
  tests/test_thermometer.py
Labels: feature

#97 Add power meter module
  data/power_meter_2022144230000Z.csv
  mao_merge_45m/__init__.py
  mao_merge_45m/merge.py
  mao_merge_45m/power_meter.py
  tests/test_power_meter.py
Labels: feature

#99 Update thermometer module
  mao_merge_45m/thermometer.py
Labels: docs

#103 Update devcontainer
  .devcontainer/devcontainer.json
Labels: environment
